---
title: "Bob Literman"
---

I am an NSF Postdoctoral Fellow (NSF: 1812201) working on developing computational methods to to identify and classify high-information and low-information subsets of phylogenomics data. This type of information can be used to increase signal-to-noise ratios, reduce computational burdens for large analyses, and gain a stronger overall understanding around how genomes, and their host species, have and continue to evolve.

I am also very interested in developing collaborative strategies to create inclusive student recruitment/retention plans to reinforce two main ideas:

1) Having solid computational skills benefits all students, regardless of their specific research interests or majors.</p>

2) A diverse pool of computationally-savvy students can help to facilitate a continuation of that diversity into the future, wherever those students choose to take their talents.

## Publications

*Years are clickable DOI Links*

<p>Radhakrishnan, S., <b>Literman, R.</b>, Neuwald, J.L., and Valenzuela,N. (In Press) Thermal response of epigenetic genes informs turtle sex determination with and without sex chromosomes. <i>Sexual Development</i></p>

<p><b>Robert Literman</b>, A. Burrett, B. Bista &amp; Valenzuela, N. (<a href="https://doi.org/10.1007/s00239-017-9820-x" target="_blank">2018</a>) Putative independent evolutionary reversals from genotypic to temperature-dependent sex determination are associated with accelerated evolution of sex-determining genes in turtles. <i>J Mol.Evol</i></p>

<p>Radhakrishnan, S., <b>Literman, R.</b>, Mizoguchi, B., &amp; Valenzuela, N. (<a href="https://doi.org/10.1186/s13072-017-0136-2" target="_blank">2017</a>). meDIP-seq and nCpG analyses illuminate sexually dimorphic methylation of gonadal development genes with high historic methylation in turtle hatchlings with temperature-dependent sex -determination. <i>Epigenetics &amp; Chromatin</i></p>

<p><b>Robert Literman</b>, S. Radhakrishnan, J. Tamplin, R. Burke, C. Dresser &amp; N. Valenzuela (<a href="https://doi.org/10.1007/s12686-017-0711-7" target="_blank">2017</a>) &ldquo;Development of sexing primers in <i>Glyptemys insculpta</i> and <i>Apalone spinifera</i> turtles uncovers an XX/XY sex-determining system in the critically-endangered bog turtle <i>Glyptemys muhlenbergii</i>.&ldquo; <i>Conservation Genetics Resources</i></p>

<p>Radhakrishnan, S., <b>Literman, R.</b>, Neuwald, J., Severin, A., Valenzuela, N. (<a href="https://doi.org/10.1371/journal.pone.0172044" target="_blank">2017</a>) “Transcriptomic responses to environmental temperature by turtles with temperature-dependent and genotypic sex determination assessed by RNAseq inform the genetic architecture of embryonic gonadal development”. <i>PLOS ONE</i></p>

<p>Twyman, H., Valenzuela, N., <b>Literman, R.</b>, Andersson, S., &amp; Mundy, N. I. (<a href="https://doi.org/10.1098/rspb.2016.1208" target="_blank">2016</a>). “Seeing red to being red: conserved genetic mechanism for red cone oil droplets and co-option for red coloration in birds and turtles”. <i>Proceedings of the Royal Society B</i></p>

<p>Montiel, E. E., Badenhorst, D., Lee L.S., <b>Literman, R.</b>, Trifonov, V., Valenzuela, N. (<a href="https://doi.org/10.1159/000447478" target="_blank">2016</a>). “Cytogenetic insights into the evolution of chromosomes and sex determination reveal striking homology of turtle sex chromosomes to amphibian autosomes”. <i>Cytogenetic and Genome Research</i></p>

<p>Badenhorst, D., Hillier, L.W., <b>Literman, R.</b>, Seven Others, Valenzuela, N. (<a href="https://doi.org/10.1093/gbe/evv119" target="_blank">2015</a>). “Physical mapping and refinement of the painted turtle genome (<i>Chrysemys picta</i>) inform amniote genome evolution and challenge turtle-bird chromosomal conservation”. <i>Genome Biology and Evolution</i></p>

<p>Janes, D. E, Seven Others, <b>Literman, R.</b>, Six Others. (<a href="https://doi.org/10.1098/rsbl.2014.0809" target="_blank">2014</a>). “Molecular evolution of Dmrt1 accompanies change of sex-determining mechanisms in Reptilia”. <i>Biology Letters</i></p>

<p><b>Literman, R.</b>, Badenhorst, D., &amp; Valenzuela, N. (<a href="https://doi.org/10.1111/2041-210X.12228" target="_blank">2014</a>). “qPCR‐based molecular sexing by copy number variation in rRNA genes and its utility for sex identification in soft‐shell turtles”. <i>Methods in Ecology and Evolution</i></p>

<p>Valenzuela, N., Badenhorst, D., Montiel, E. E., &amp; <b>Literman, R.</b> (<a href="https://doi.org/10.1111/2041-210X.12228" target="_blank">2014</a>). “Molecular cytogenetic search for cryptic sex chromosomes in painted turtles <i>Chrysemys picta</i>”. <i>Cytogenetic and Genome Research</i></p>

<p>Shaffer, H. Bradley, et al. (<a href="https://doi.org/10.1186/gb-2013-14-3-r28" target="_blank">2013</a>) &ldquo;The western painted turtle genome, a model for the evolution of extreme physiological adaptations in a slowly evolving lineage.&ldquo; <i>Genome Biology</i></p>

<p>Valenzuela, N., Neuwald, J. L., &amp; <b>Literman, R.</b> (<a href="https://doi.org/10.1002/dvdy.23897" target="_blank">2013</a>). “Transcriptional evolution underlying vertebrate sexual development”. <i>Developmental Dynamics</i></p>

<p>Zhang, W., Ahluwalia, I. P., <b>Literman, R.</b>, Kaplan, D. L., &amp; Yelick, P. C. (<a href="https://doi.org/10.1002/jbm.a.33062" target="_blank">2011</a>). “Human dental pulp progenitor cell behavior on aqueous and hexafluoroisopropanol based silk scaffolds”. <i>Journal of Biomedical Materials Research Part A</i></p>