---
title: "Graduate Student Position"
---

PhD or Masters Student position in Phylogenomics / Bioinformatics 

A graduate student position is available in the Schwartz Lab in the College of the Life Sciences and the Environment at the University of Rhode Island to work on projects in phylogenomics starting in Fall 2021. 
The lab is focused on understanding evolutionary history using genomic datasets. 
We also develop methods and software for researchers interested in empirical questions. 
The student will be expected use computational tools to examine phylogenetic datasets,
but will have some flexibility to develop a project related to their interest.
Opportunities for collaboration at URI and elsewhere are also possible.

Required skills and expectations:

* B.S. or M.S. in Evolution or Bioinformatics or a related field (e.g. Biology)
* Background and interest in phylogenetics and evolution
* Commitment to participating in a collaborative and inclusive lab environment
* Prior research experience (e.g. summer internship, work in research lab)
* Interest in computational research

Preferred skills: 

* Experience with genetic sequence data including building phylogenies
* Experience coding in R, Python, or another language
* Experience working in an HPC environment
* Demonstrated writing skills

This position will be partly funded by URI RA support and partly by an NSF grant. The student will also be expected to TA (for example Introductory Biology lab). Students from backgrounds that have been excluded from science due to ethnicity or race are particularly encouraged to apply. 

Location: URI is located in the southern part of Rhode Island, approximately a 40 minute drive from Providence and a 10 minute drive to multiple beaches. The Schwartz Lab is housed on the main URI campus in Kingston in the new Center for Biotechnology and the Life Sciences.

The student will be a part of the [Biological and Environmental Sciences graduate program](http://web.uri.edu/cels-gradprograms/bes/) in the College of the Environement and Life Sciences, with a specialization in [Evolutionary Biology](https://web.uri.edu/cels-gradprograms/bes/emb/) or [Cell and Molecular Biology](https://web.uri.edu/cels-gradprograms/bes/cmb/). 

For more information please read the [expectations and responsibilities](positions.html). Prior to applying to the graduate program please send your CV and a cover letter (rsschwartz@uri.edu) outlining your research interest and how they might intersect with mine. 